package df.open.statistic.core.dao;

import df.open.statistic.core.model.SInvokerHis;

public interface SInvokerHisMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_invoker_his
     *
     * @mbggenerated
     */
    int insert(SInvokerHis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_invoker_his
     *
     * @mbggenerated
     */
    int insertSelective(SInvokerHis record);
}