package df.open.statistic.core.dao;

import df.open.statistic.core.model.SProject;
import df.open.statistic.core.model.SProjectExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SProjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_project
     *
     * @mbggenerated
     */
    int countByExample(SProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_project
     *
     * @mbggenerated
     */
    int deleteByExample(SProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_project
     *
     * @mbggenerated
     */
    int insert(SProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_project
     *
     * @mbggenerated
     */
    int insertSelective(SProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_project
     *
     * @mbggenerated
     */
    List<SProject> selectByExample(SProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_project
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SProject record, @Param("example") SProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_project
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SProject record, @Param("example") SProjectExample example);
}