package df.open.statistic.core.model;

public class SInvokerHis {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_invoker_his.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_invoker_his.id
     *
     * @return the value of s_invoker_his.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_invoker_his.id
     *
     * @param id the value for s_invoker_his.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }
}