package df.open.statistic.core.model;

import java.math.BigDecimal;
import java.util.Date;

public class SInvoker {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_invoker.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_invoker.type
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_invoker.project
     *
     * @mbggenerated
     */
    private String project;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_invoker.class_name
     *
     * @mbggenerated
     */
    private String className;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_invoker.method_name
     *
     * @mbggenerated
     */
    private String methodName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_invoker.parent_class_name
     *
     * @mbggenerated
     */
    private String parentClassName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_invoker.parent_method_name
     *
     * @mbggenerated
     */
    private String parentMethodName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_invoker.cost
     *
     * @mbggenerated
     */
    private BigDecimal cost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_invoker.count
     *
     * @mbggenerated
     */
    private Integer count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_invoker.result
     *
     * @mbggenerated
     */
    private Integer result;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_invoker.invoke_time
     *
     * @mbggenerated
     */
    private Date invokeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_invoker.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_invoker.id
     *
     * @return the value of s_invoker.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_invoker.id
     *
     * @param id the value for s_invoker.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_invoker.type
     *
     * @return the value of s_invoker.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_invoker.type
     *
     * @param type the value for s_invoker.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_invoker.project
     *
     * @return the value of s_invoker.project
     *
     * @mbggenerated
     */
    public String getProject() {
        return project;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_invoker.project
     *
     * @param project the value for s_invoker.project
     *
     * @mbggenerated
     */
    public void setProject(String project) {
        this.project = project == null ? null : project.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_invoker.class_name
     *
     * @return the value of s_invoker.class_name
     *
     * @mbggenerated
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_invoker.class_name
     *
     * @param className the value for s_invoker.class_name
     *
     * @mbggenerated
     */
    public void setClassName(String className) {
        this.className = className == null ? null : className.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_invoker.method_name
     *
     * @return the value of s_invoker.method_name
     *
     * @mbggenerated
     */
    public String getMethodName() {
        return methodName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_invoker.method_name
     *
     * @param methodName the value for s_invoker.method_name
     *
     * @mbggenerated
     */
    public void setMethodName(String methodName) {
        this.methodName = methodName == null ? null : methodName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_invoker.parent_class_name
     *
     * @return the value of s_invoker.parent_class_name
     *
     * @mbggenerated
     */
    public String getParentClassName() {
        return parentClassName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_invoker.parent_class_name
     *
     * @param parentClassName the value for s_invoker.parent_class_name
     *
     * @mbggenerated
     */
    public void setParentClassName(String parentClassName) {
        this.parentClassName = parentClassName == null ? null : parentClassName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_invoker.parent_method_name
     *
     * @return the value of s_invoker.parent_method_name
     *
     * @mbggenerated
     */
    public String getParentMethodName() {
        return parentMethodName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_invoker.parent_method_name
     *
     * @param parentMethodName the value for s_invoker.parent_method_name
     *
     * @mbggenerated
     */
    public void setParentMethodName(String parentMethodName) {
        this.parentMethodName = parentMethodName == null ? null : parentMethodName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_invoker.cost
     *
     * @return the value of s_invoker.cost
     *
     * @mbggenerated
     */
    public BigDecimal getCost() {
        return cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_invoker.cost
     *
     * @param cost the value for s_invoker.cost
     *
     * @mbggenerated
     */
    public void setCost(BigDecimal cost) {
        this.cost = cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_invoker.count
     *
     * @return the value of s_invoker.count
     *
     * @mbggenerated
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_invoker.count
     *
     * @param count the value for s_invoker.count
     *
     * @mbggenerated
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_invoker.result
     *
     * @return the value of s_invoker.result
     *
     * @mbggenerated
     */
    public Integer getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_invoker.result
     *
     * @param result the value for s_invoker.result
     *
     * @mbggenerated
     */
    public void setResult(Integer result) {
        this.result = result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_invoker.invoke_time
     *
     * @return the value of s_invoker.invoke_time
     *
     * @mbggenerated
     */
    public Date getInvokeTime() {
        return invokeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_invoker.invoke_time
     *
     * @param invokeTime the value for s_invoker.invoke_time
     *
     * @mbggenerated
     */
    public void setInvokeTime(Date invokeTime) {
        this.invokeTime = invokeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_invoker.create_time
     *
     * @return the value of s_invoker.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_invoker.create_time
     *
     * @param createTime the value for s_invoker.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}